energy_website/blog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from django.contrib.sitemaps.views import sitemap

from blog.sitemaps import(
    StaticViewSitemap,
    ArticleSitemap,
    CategorySitemap
)

sitemaps = {
    "static": StaticViewSitemap,
    "article": ArticleSitemap,
    "category": CategorySitemap
}

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('about/', views.about, name='blog-about'),
    path('sitemap.xml/', sitemap, {"sitemaps" : sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path(
        "robots.txt/",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    url(r'^article/(?P<slug>[\w-]+)/$', views.article_detail, name='link'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.list_by_category, name='list_by_category'),
    
]

energy_website/energy_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()

energy_website/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse

# Create your models here.
STATUS = (
    (0,"Draft"),
    (1,"Publish")
)
class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('blog:list_by_category', args=[self.slug] )

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    content = RichTextField(config_name = 'default')
    summary = models.CharField(max_length=100)
    datePosted = models.DateTimeField(auto_now_add=True)
    author = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def snippet(self):
        return self.content[:100]
    
    def get_absolute_url(self):
        return reverse('blog:link', args=[self.slug] )

class Comment(models.Model):
    post = models.ForeignKey(Article,on_delete=models.CASCADE,related_name='comments', null=True)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

energy_website/blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

energy_website/blog/views.py
from django.http import HttpResponse
from .models import Article, Comment, Category
from .forms import CommentForm
from django.shortcuts import render, get_object_or_404
# Create your views here.

def list_by_category(request, category_slug):
    categories = Category.objects.all()
    articles = Article.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        articles = articles.filter(category=category)
    context = {'categories': categories, 'articles': articles, 'category': category}
    return render(request, 'blog/categories.html', context)

def home(request):
    articles = Article.objects.all()
    return render(request, 'blog/home.html', {'articles':articles})

def about(request):
    return render(request, 'blog/about.html',)

def article_detail(request, slug):
    articles = get_object_or_404(Article, slug=slug)
    comments = articles.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.articles = articles
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'blog/article_template.html', {'articles':articles, 'comments': comments,
                                                            'new_comment': new_comment,
                                                            'comment_form': comment_form})

energy_website/blog/templates/blog/about.html
{% extends "blog/info_base.html" %}
{% load static %}
{% block head %}
  <title>About Page | Demystifying Energy</title>
  <meta name="description" content="A place to learn about energy, basic physics concepts while being easy to understand. No ads. For students, by students.">
  <meta property="og:description" content="A place to learn about energy, basic physics concepts while being easy to understand. No ads. For students, by students.">

  <meta name="twitter:description" content="A place to learn about energy, basic physics concepts while being easy to understand. No ads. For students, by students.">
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="About Page | Demystifying Energy" />
{% endblock %}
{% block content %}
<div class="parallax-container" id='parallax-about'>
  <div class="jumbotron jumbotron-fluid" id="jumbotron-about">
    <div class="container">
      <h1 class="display-4 lora">About Us</h1>
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, assumenda?</p>
    </div>
    <img src="{% static 'blog/img/transparent.png' %}" class="background-image">
  </div>
  <div class="parallax test-change"><img src="https://images.unsplash.com/photo-1483794344563-d27a8d18014e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80"></div>
</div>

{% endblock content %}

energy_website/blog/templates/blog/article_template.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700|Montserrat:300" rel="stylesheet">
    
    <!--Website Icon-->
    <link rel="icon" href="{% static 'blog/img/Logo.png' %}" type="image/png" />

    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'blog/articles.css' %}">



  
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="{{articles.title}}. Easy to understand. No ads. For students, by students.">
    <meta property="og:description" content="{{articles.title}}. Easy to understand. No ads. For students, by students.">

    <meta name="twitter:description" content="{{articles.title}}. Easy to understand. No ads. For students, by students.">
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="Learn {{articles.title}} | Demystifying Energy" />

    <title>{{ articles.title }} | Demystifying Energy</title>

    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  </head>
  <body>
    <nav class="z-depth-0">
      <div class="nav-wrapper container">
        <a href="{% url 'blog:blog-home'%}" class="brand-logo lora">Demystifying Energy</a>

        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons" style="color: #2D3047">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'blog:blog-about'%}">About</a></li>
        </ul>

      </div>
    </nav>
    <ul id="nav-mobile" class="sidenav" >
      <li><a href="{% url 'blog:blog-home' %}">Home</a></li>
      <li><a href="{% url 'blog:blog-about' %}">About</a></li>
    </ul>
    <div class="container article-container">
      <div class="row">
        <div class="col s12">
          <article class="content-section">
            <div class="article-metadata">
              <h1>{{articles.title}}</h1>
              <h6>By <a class="mr-2" href="#">{{articles.author}}</a>
                <small class="text-muted">{{articles.datePosted}}</small>
                Category: <a class ="mr-2" href="{{articles.category.get_absolute_url}}"> {{ articles.category }}</a>
              </h6>
            </div>
            <p>{{articles.content | safe}}</p>
          </article>
          <div class="content-section">
            <div class="card-body">
              <!-- comments -->
              <h4>{{ comments.count }} Comment(s)</h4>
              {% for comment in comments %}
                <div class="comments">
                  <h6><span class="name">{{ comment.name }}</span>
                    <small class="text-muted">{{ comment.created_on }}</small></h6>
                  {{ comment.body | linebreaks }}
                </div>
              {% endfor %}
            </div>
          </div>
          <div class="content-section">
            <div class="card-body">
              {% if new_comment %}
              <div class="alert alert-success" role="alert">
                Your comment is awaiting moderation
              </div>
              {% else %}
              <h4>Leave a comment</h4>
              <form method="post" style="margin-top: 1.3em;">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
              </form>
              {% endif %}
            </div>
          </div>
          <div class="col s12">
            <h5>Related Articles</h5>
            <div class="content-section">
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <!--JavaScript at end of body for optimized loading-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'blog/init.js' %}"></script>
    <script src="{% static 'blog/materialize.js'%}"></script>
    
  </body>
</html>

energy_website/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <meta name="google-site-verification" content="O0B3rmBbDvazdYrhebmdtxrvQ_pJwDpsZp27vP4itgo" />
    
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700|Montserrat:300" rel="stylesheet">

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700|Montserrat:300" rel="stylesheet">

    <!--Website Icon-->
    <link rel="icon" href="{% static 'blog/img/Logo.png' %}" type="image/png" sizes="512x512"/>

    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">

    {% block head %} {% endblock %}
</head>
<body>
    <nav class="z-depth-0">
      <div class="nav-wrapper container">
        <a href="{% url 'blog:blog-home'%}" class="brand-logo lora">Demystifying Energy</a>

        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons" style="color: #2D3047">menu</i></a>


        <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'blog:blog-about'%}">About</a></li>
        </ul>

      </div>
    </nav>
    <ul id="nav-mobile" class="sidenav" >
      <li><a href="{% url 'blog:blog-home' %}">Home</a></li>
      <li><a href="{% url 'blog:blog-about' %}">About</a></li>
    </ul>

    {% block content %}
    {% endblock %}

    <div class="col s4">
        <div class="content-section">
            <h3 class="side-panel">Categories</h3>
            <p class='text-muted'>
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light"><a href="/category/physics-concepts">Physics Concepts</a></li>
                    <li class="list-group-item list-group-item-light"><a href="/category/generation">Generation</a></li>
                    <li class="list-group-item list-group-item-light"><a href="/category/transmission">Transmission</a></li>
                    <li class="list-group-item list-group-item-light"><a href="/category/consumption">Consumption & Usage</a></li>
                    <li class="list-group-item list-group-item-light"><a href="/category/energy-malaysia">Energy in Malaysia</a></li>
                </ul>
            </p>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'blog/init.js' %}"></script>
    <script src="{% static 'blog/materialize.js'%}"></script>
</body>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->



</html>

energy_website/blog/templates/blog/categories.html
{% extends "blog/base.html" %}
{% block head %}
  <title>Learn {{category.name}} | Demystifying Energy</title>
  <meta name="description" content="Learn about the {{category.name}} topic that is explained in a simple manner. No ads. For students, by students.">
  <meta property="og:description" content="Learn about the {{category.name}} topic that is explained in a simple manner. No ads. For students, by students.">

  <meta name="twitter:description" content="Learn about the {{category.name}} topic that is explained in a simple manner. No ads. For students, by students.">
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Learn {{category.name}} | Demystifying Energy" />
{% endblock %}

{% block content %}
<div class="container" style="padding-top:20vh">
  <h1 class="display-4 lora" id="jumbotron-title">{{category.name}}</h1>
</div>

<main role="main" class="container content">
<div class="row">
    <div class="col s8">
      {% for article in articles %}
        {% if article.status%}
        <article class="media content-section">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="#">{{ article.author }}</a>
                <small class="text-muted">{{ article.datePosted }}</small>
                <a class="mr-2" href="{{article.category.get_absolute_url}}">{{article.category}}</a>
              </div>
              <h2><a class="article-title" href="{% url 'blog:link' slug=article.slug %}">{{ article.title }}</a></h2>
              <p class="article-content">{{ article.summary}}</p>
            </div>
          </article>
        {% endif %}
      {% endfor %}
    </div>

{% endblock content %}

energy_website/blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load static %}
{% block head %}
  <title>Demystifying Energy | Learn about energy</title>
  <meta name="description" content="Learn about energy, basic physics concepts that are explained in a simple manner. No ads. For students, by students.">
  <meta property="og:description" content="Learn about energy, basic physics concepts that are explained in a simple manner. No ads. For students, by students.">

  <meta name="twitter:description" content="Learn about energy, basic physics concepts that are explained in a simple manner. No ads. For students, by students.">
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Demystifying Energy | Learn about energy" />
{% endblock %}

{% block content %}

<div class="parallax-container">
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4 lora" id="jumbotron-title">WELCOME</h1>
      <p class="lead">The team will be posting content related to energy, ranging from  physics concepts to transmission.</p>
    </div>
    <img src="{% static 'blog/img/transparent.png' %}" class="background-image">
  </div>
</div>

<main role="main" class="container content">
<div class="row">
    <div class="col s8">
      {% for article in articles %}
        {% if article.status%}
        <article class="media content-section">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="#">{{ article.author }}</a>
                <small class="text-muted">{{ article.datePosted }}</small>
                <a class="mr-2" href="{{article.category.get_absolute_url}}">{{article.category}}</a>
              </div>
              <h2><a class="article-title" href="{% url 'blog:link' slug=article.slug %}">{{ article.title }}</a></h2>
              <p class="article-content">{{ article.summary}}</p>
            </div>
          </article>
        {% endif %}
      {% endfor %}
    </div>

{% endblock content %}

energy_website/blog/templates/blog/info_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <meta name="google-site-verification" content="O0B3rmBbDvazdYrhebmdtxrvQ_pJwDpsZp27vP4itgo" />
    
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700|Montserrat:300" rel="stylesheet">

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700|Montserrat:300" rel="stylesheet">

    <!--Website Icon-->
    <link rel="icon" href="{% static 'blog/img/Logo.png' %}" type="image/png" sizes="256x256"/>

    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">

    {% block head %} {% endblock %}

</head>
<body>
    <nav class="z-depth-0">
      <div class="nav-wrapper container">
        <a href="{% url 'blog:blog-home'%}" class="brand-logo lora">Demystifying Energy</a>

        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons" style="color: #2D3047">menu</i></a>


        <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'blog:blog-about'%}">About</a></li>
        </ul>

      </div>
    </nav>
    <ul id="nav-mobile" class="sidenav" >
      <li><a href="{% url 'blog:blog-home' %}">Home</a></li>
      <li><a href="{% url 'blog:blog-about' %}">About</a></li>
    </ul>

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'blog/init.js' %}"></script>
    <script src="{% static 'blog/materialize.js'%}"></script>
</body>


</html>